### ISSUE TITLE
[BUG] 1.20.5 

### ISSUE THREAD

**Issue by SonnenPingu** [KaspianDev/AntiPopup#85] opened 2024-04-28 08:03 UTC
### Describe the bug

[08:49:56] [Server thread/INFO]: [AntiPopup] Loading server plugin AntiPopup v7.3-HOTFIX
[08:49:56] [Server thread/WARN]: [AntiPopup] [packetevents] We currently do not support the minecraft version 1.20.5, so things might break. PacketEvents will behave as if the minecraft version were 1.20.4!
[08:49:56] [Server thread/ERROR]: [AntiPopup] Error initializing plugin 'AntiPopup-7.3-HOTFIX.jar' in folder 'plugins/.paper-remapped' (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.get(Object)" because the return value of "com.github.kaspiandev.antipopup.libs.packetevents.util.reflection.Reflection.getField(java.lang.Class, java.lang.Class, int)" is null
	at AntiPopup-7.3-HOTFIX.jar/com.github.kaspiandev.antipopup.libs.packetevents.util.SpigotReflectionUtil.getMinecraftServerInstance(SpigotReflectionUtil.java:319) ~[AntiPopup-7.3-HOTFIX.jar:?]
	at AntiPopup-7.3-HOTFIX.jar/com.github.kaspiandev.antipopup.libs.packetevents.util.SpigotReflectionUtil.getMinecraftServerConnectionInstance(SpigotReflectionUtil.java:330) ~[AntiPopup-7.3-HOTFIX.jar:?]
	at AntiPopup-7.3-HOTFIX.jar/com.github.kaspiandev.antipopup.libs.packetevents.injector.SpigotChannelInjector.isServerBound(SpigotChannelInjector.java:63) ~[AntiPopup-7.3-HOTFIX.jar:?]
	at AntiPopup-7.3-HOTFIX.jar/com.github.kaspiandev.antipopup.libs.packetevents.factory.spigot.SpigotPacketEventsBuilder$1.load(SpigotPacketEventsBuilder.java:115) ~[AntiPopup-7.3-HOTFIX.jar:?]
	at AntiPopup-7.3-HOTFIX.jar/com.github.kaspiandev.antipopup.AntiPopup.onLoad(AntiPopup.java:54) ~[AntiPopup-7.3-HOTFIX.jar:?]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.20.5.jar:git-Paper-6]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.20.5.jar:git-Paper-6]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.20.5.jar:git-Paper-6]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.5.jar:git-Paper-6]
	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:508) ~[paper-1.20.5.jar:git-Paper-6]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:287) ~[paper-1.20.5.jar:git-Paper-6]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1140) ~[paper-1.20.5.jar:git-Paper-6]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.5.jar:git-Paper-6]
	at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]

### To Reproduce

Download paper 1.20.5 
Paste the plugin into the folder 

### Operating System

Ubuntu

### Server Software

Paper 1.20.5

### Server Version

1.20.1

### Proxy Type

Velocity

### Plugin List

```bash
AntiPopup
```

### Server logs

https://mpx.wtf/wivakitula.log

**Comment by KaspianDev** [comment] 2024-04-28 09:30
Duplicate of #84

**Closed by KaspianDev** 2024-04-28 09:30 UTC
Labels: bug
