### ISSUE TITLE
[BUG] Update PacketEvents to fix ViaVersion issues 

### ISSUE THREAD

**Issue by F3F5** [KaspianDev/AntiPopup#82] opened 2024-04-06 21:04 UTC
### Describe the bug

check this - https://github.com/Bram1903/MinecraftPlayerCrasher/issues/4

### To Reproduce

i have the simillar issues 

[10:00:13] [Netty Epoll Server IO #1/INFO]: [packetevents] Unable to grab ViaVersion client version for player!
[10:00:13] [Netty Epoll Server IO #1/INFO]: [AntiPopup] [STDOUT] Unable to grab ViaVersion client version for player!
[10:00:13] [Netty Epoll Server IO #1/WARN]: Nag author(s): '[Kaspian]' of 'AntiPopup v7.3' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).

### Expected behavior

.

### Operating System

Ubuntu

### Server Software

1.20.4 Paper

### Server Version

Not Listed

### Proxy Type

None

### Plugin List

```bash
AntiPopup
```

### Server logs

why

**Comment by F3F5** [comment] 2024-04-06 23:29
https://github.com/KaspianDev/AntiPopup/pull/83

**Comment by KaspianDev** [comment] 2024-04-07 16:00
Duplicate of #78 (scheduled to be fixed in future release)

**Closed by KaspianDev** 2024-04-07 16:00 UTC
Labels: bug
