### ISSUE TITLE
[BUG] Log spam caused by PacketProcessException

### ISSUE THREAD

**Issue by velnias75** [KaspianDev/AntiPopup#39] opened 2023-02-04 11:06 UTC
### Describe the bug

The server log is spammed with yellow stacktraces of
`Caused by: com.github.kaspiandev.antipopup.libs.com.github.retrooper.packetevents.exception.PacketProcessException: Failed to map the Packet ID 25 to a PacketType constant. Bound: CLIENT, Connection state: STATUS, Server version: 1.19.2` surrounded by a full large stacktrace.

It occurs frequently, even if the server is idle, i.e. no player is logged in or no login attempt is in the logs.

### To Reproduce

Just watch the log …

### Expected behavior

At least not the full Stacktrace, better no message at all, since the server stays running well.

### Operating System

Ubuntu 20.04.5 LTS (focal)

### Server Software

Paper version git-Paper-307

### Server Version

1.19.2

### Proxy Type

None

### Plugin List

```bash
AntiPopup, ColoredSigns, CoreProtect, DiscordSRV, dynmap, EzHomes, Graves, Images, JoinMessage, LuckPerms, NoMobGriefing, PangaeaBlocks, PhatLoots, PinkBull, ProtocolLib, RainManNG, RHSignItem, SEC, ServerBackup, Shopkeepers, spark, TAB, TABWorldDate, ViewDistanceTweaks, VipSlot*, XItemsRemover
```

### Server logs

-

**Comment by KaspianDev** [comment] 2023-02-04 12:07
Duplicate of #37

**Closed by KaspianDev** 2023-02-04 12:07 UTC
Labels: bug, duplicate, can't reproduce

**Comment by velnias75** [comment] 2023-02-04 12:14
My error has Packert ID 25, and it is 1.19.2

**Comment by KaspianDev** [comment] 2023-02-04 12:15
shouldnt matter i think

**Comment by velnias75** [comment] 2023-02-04 12:18
All posted logs in #37 show error 23.

I tried the 5.4-RC1 today, but it got in an endless loop (if stacktraces)

**Comment by KaspianDev** [comment] 2023-02-04 13:05
> All posted logs in #37 show error 23.
> 
> I tried the 5.4-RC1 today, but it got in an endless loop (of stacktraces)

5.4-rc1 is broken

**Comment by SlimeDog** [comment] 2023-02-08 06:32
I just got this one, with AntiPopup 5.2 on Spigot 1.19.3-3649.
