### ISSUE TITLE
[BUG] DecoderException: Longarray with size X is bigger than allowed Y

### ISSUE THREAD

**Issue by paul-eff** [KaspianDev/AntiPopup#66] opened 2023-10-03 21:39 UTC
### Describe the bug

I can join my server but after max 20 seconds I get an error like the following and it kicks me from the server: 
Internal Exception; io.netty.handler.codec.DecoderException: Longarray with size 113 is bigger than allowed 3

I am aware of "[AntiPopup] [packetevents] We currently do not support the minecraft version 1.20.2, so things might break. PacketEvents will behave as if the minecraft version were 1.20.1!".
Just wanted to give a heads up where problems may arise.

### To Reproduce

1. Have a Paper 1.20.2 207 server
2. Install AntiPopup 6.2
3. Problem

### Expected behavior

It should work normally, not kick me.

### Operating System

Ubuntu 20.04.4 LTS

### Server Software

Paper 1.20.2 207

### Server Version

Not Listed

### Proxy Type

None

### Plugin List

```bash
AntiPopup, WorldEdit, Dynmap, DriveBackupV2
```

### Server logs

https://pastebin.com/2cnz6DTb

**Comment by KaspianDev** [comment] 2023-10-04 13:35
Duplicate of #45

**Closed by KaspianDev** 2023-10-04 13:35 UTC
Labels: bug
